//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.TextSource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test2.TextSource.RHome", typeof(RHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string MAboutUs {
            get {
                return ResourceManager.GetString("MAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas of Activity.
        /// </summary>
        public static string MAREASOFACTIVITY {
            get {
                return ResourceManager.GetString("MAREASOFACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attorney.
        /// </summary>
        public static string MAttorney {
            get {
                return ResourceManager.GetString("MAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MContact {
            get {
                return ResourceManager.GetString("MContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string MGetInTouch {
            get {
                return ResourceManager.GetString("MGetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MHome {
            get {
                return ResourceManager.GetString("MHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Are.
        /// </summary>
        public static string MHowWeAre {
            get {
                return ResourceManager.GetString("MHowWeAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string MNews {
            get {
                return ResourceManager.GetString("MNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string MOthers {
            get {
                return ResourceManager.GetString("MOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR ATTORNEYS.
        /// </summary>
        public static string MOURATTORNEYS {
            get {
                return ResourceManager.GetString("MOURATTORNEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Firm News.
        /// </summary>
        public static string MOurFirmNews {
            get {
                return ResourceManager.GetString("MOurFirmNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MServices {
            get {
                return ResourceManager.GetString("MServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE GREATEST FIRM YOU CAN TRUST.
        /// </summary>
        public static string MTHEGreate {
            get {
                return ResourceManager.GetString("MTHEGreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &amp; COMING.
        /// </summary>
        public static string MUPDATECOMING {
            get {
                return ResourceManager.GetString("MUPDATECOMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string MWELCOME {
            get {
                return ResourceManager.GetString("MWELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT WE DO.
        /// </summary>
        public static string MWHATWEDO {
            get {
                return ResourceManager.GetString("MWHATWEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
    }
}
